#version: "3.9"

services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: ax-mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ${PWD}/infrastructure/mosquitto/config:/mosquitto/config:ro
      - ${PWD}/infrastructure/mosquitto/data:/mosquitto/data
      - ${PWD}/infrastructure/mosquitto/log:/mosquitto/log
    mem_limit: 512m
    cpus: 0.50
    networks:
      - ax-network
  
  postgres:
    image: postgres:16.2
    container_name: ax-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: iot_db
      POSTGRES_USER: iot_user
      POSTGRES_PASSWORD: iot_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    mem_limit: 512m
    cpus: 0.5
    ports:
      - "5432:5432"
    networks:
      - ax-network

  ingestor:
    build: 
      context: ./infrastructure/ingestor
    image: neta_cero-ingestor:v1.0
    container_name: ax-ingestor
    restart: unless-stopped
    depends_on:
      - postgres
      - mosquitto
    environment:
      MQTT_BROKER: mosquitto
      MQTT_PORT: 1883
      MQTT_TOPIC: sensor/#
      DATABASE_URL: postgresql://iot_user:iot_password@postgres:5432/iot_db
    networks:
      - ax-network
    mem_limit: 512m
    cpus: 0.5
       
      
  grafana:
    image: grafana/grafana-oss:11.5.1
    container_name: ax-grafana
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - ax-network
    mem_limit: 512m
    cpus: 0.50

  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    profiles: ["dev"]
    image: neta_cero-dev:v1.0
    container_name: ax-devs
    working_dir: /workspace
    volumes:
      - ./:/workspace:cached
    ports:
      - "18000:8000"
    networks:
      - ax-network
    command: sleep infinity
  
  wireshark:
    image: lscr.io/linuxserver/wireshark
    container_name: ax-wireshark
    cap_add:
      - NET_ADMIN
    network_mode: host
    ports:
      - "3000:3000"
    restart: unless-stopped
    mem_limit: 512m
    cpus: 0.50
volumes:
  postgres_data:
  grafana_data:
networks:
  ax-network:
    driver: bridge
